refactor: small code improvements
cpeditor/QCodeEditor pull request #36
Opened 2021-05-09 09:43 UTC by knarfS

As your fork of QCodeEditor is the only one that is somewhat maintained (although deprecated) and receives pull requests, I'd appreciate it if you merge my changes so that our forks are in sync.

What I've done:
- Fix various clazy warnings.
- Let CMake generate a `compile_commands.json` for other static code analysis tools.
- Add a `.editorconfig` to reflect the different indentation sizes.
- Update `.gitignore` for the use of kdevelop.
- Add suppport for older Qt versions (>= 5.7)

Please let me know what you think. Maybe you f.e. prefer pull requests for the individual changes?

2021-05-15 12:54 UTC, ouuan requested changes

2021-05-15 12:54 UTC, ouuan commented on src/internal/QCodeEditor.cpp
> +                          .arg(backgroundColor, selectionBackground, textColor));
I think it's a good habit to use multiple `.arg`s. Sometimes using a single `.arg` results in the same, but when there are some integers in the args, it could unexpectedly match overloads like `QString QString::arg(QLatin1String a, int fieldWidth = 0, QChar fillChar = QLatin1Char(' ')) const`.

2021-05-15 12:54 UTC, ouuan commented on .editorconfig
> +indent_size = 2
```suggestion
indent_size = 4
```

2021-05-16 13:09 UTC, knarfS commented on src/internal/QCodeEditor.cpp
> +                          .arg(backgroundColor, selectionBackground, textColor));
To avoid unnecessary heap allocations, the use of `QString::arg()` with multiple arguments is preferred.

Actually clazy is detecting the use of misleading overloads, like the one you pointed out. See: https://github.com/KDE/clazy/blob/master/docs/checks/README-qstring-arg.md

2021-05-16 13:17 UTC, knarfS commented on .editorconfig
> +indent_size = 2
I was just checking this and unfortunately the header files are using a uncommon mix of 2- and 4-space indentations.
I would suggest to use 4 spaces for indentation and change the headers to the following more common style (cut down example of `QLineNumberArea.hpp`):
```cpp
#pragma once

#include <QCodeEditor>
class QSyntaxStyle;

class QLineNumberArea : public QWidget
{
    Q_OBJECT

public:
    explicit QLineNumberArea(QCodeEditor *parent = nullptr);
    QLineNumberArea(const QLineNumberArea &) = delete;
    QLineNumberArea &operator=(const QLineNumberArea &) = delete;
    void setSyntaxStyle(QSyntaxStyle *style);

protected:
    void paintEvent(QPaintEvent *event) override;

private:
    QSyntaxStyle *m_syntaxStyle;
    QCodeEditor *m_codeEditParent;

};

```

2021-05-16 13:20 UTC, knarfS commented
Thanks @ouuan for your review!

2021-05-16 14:47 UTC, knarfS commented on src/internal/QCodeEditor.cpp
> +                          .arg(backgroundColor, selectionBackground, textColor));
There are more pitfalls with multiple `QString::arg()` described here: https://doc.qt.io/qt-5/qstring.html#arg-14

2021-05-22 17:32 UTC, ouuan commented on .editorconfig
> +indent_size = 2
Fine. However, I'm not sure how editorconfig is useful when we are mainly using clang-format.

2021-06-05 02:03 UTC, ouuan approved these changes

2021-06-05 02:05 UTC, merged

2021-06-13 14:20 UTC, knarfS commented
@ouuan, sorry for my late reply, but first of all: Thanks for merging!

Regarding the `.editorconfig` (https://editorconfig.org), this isn't a replacement/substitute for a `.clang-format`, but rather a simple and widespread way for a basic configuration for many editors/IDEs, like indent style (space/tab), indent_size and line ending (\n or \r\n).
Many editors support an `.editorconfig` file out of the box (see https://editorconfig.org/#pre-installed), others need a plugin (see https://editorconfig.org/#download).